import cv2

# 这里就可以正常导入，与nn46内的cv2导入报错，问题不一样，也不知道到底咋回事